from django.urls import path
from .views import (
    home,
    books_page,
    book_detail_page,
    category_page,
    cart_page,
    checkout_page,
    orders_page,
    login_page,
    register_page,
    staff_login_page,
    staff_dashboard_page,
    staff_books_page,
    staff_customers_page,
    staff_orders_page,
    staff_catalog_page,
    BooksAPI,
    BookDetailAPI,
    CartAPI,
    CartItemAPI,
    OrderAPI,
    OrderDetailAPI,
    CancelOrderAPI,
    CustomerLoginAPI,
    StaffLoginAPI,
    CustomerRegisterAPI,
    RecommendationsAPI,
    CustomersAPI,
    CategoriesAPI,
    AuthorsAPI,
    PublishersAPI,
    TagsAPI,
    ReviewsAPI,
    RatingsAPI,
    HealthCheck,
)

urlpatterns = [
    # Web UI
    path("", home, name="home"),
    path("books/", books_page, name="books"),
    path("books/<uuid:book_id>/", book_detail_page, name="book-detail"),
    path("categories/<slug:slug>/", category_page, name="category"),
    path("cart/", cart_page, name="cart"),
    path("checkout/", checkout_page, name="checkout"),
    path("orders/", orders_page, name="orders"),
    path("login/", login_page, name="login"),
    path("register/", register_page, name="register"),
    # Staff Web UI
    path("staff/login/", staff_login_page, name="staff-login"),
    path("staff/dashboard/", staff_dashboard_page, name="staff-dashboard"),
    path("staff/books/", staff_books_page, name="staff-books"),
    path("staff/customers/", staff_customers_page, name="staff-customers"),
    path("staff/orders/", staff_orders_page, name="staff-orders"),
    path("staff/catalog/", staff_catalog_page, name="staff-catalog"),
    # API Proxy
    path("api/books/", BooksAPI.as_view(), name="api-books"),
    path("api/books/<uuid:book_id>/", BookDetailAPI.as_view(), name="api-book-detail"),
    path("api/cart/<uuid:customer_id>/", CartAPI.as_view(), name="api-cart"),
    path(
        "api/cart/<uuid:customer_id>/items/<uuid:book_id>/",
        CartItemAPI.as_view(),
        name="api-cart-item",
    ),
    path("api/orders/", OrderAPI.as_view(), name="api-orders"),
    path(
        "api/orders/<uuid:customer_id>/", OrderAPI.as_view(), name="api-orders-customer"
    ),
    path(
        "api/orders/<uuid:order_id>/detail/",
        OrderDetailAPI.as_view(),
        name="api-order-detail",
    ),
    path(
        "api/orders/<uuid:order_id>/cancel/",
        CancelOrderAPI.as_view(),
        name="api-order-cancel",
    ),
    path("api/auth/login/", CustomerLoginAPI.as_view(), name="api-login"),
    path("api/auth/staff/login/", StaffLoginAPI.as_view(), name="api-staff-login"),
    path("api/auth/register/", CustomerRegisterAPI.as_view(), name="api-register"),
    path(
        "api/recommendations/<uuid:customer_id>/",
        RecommendationsAPI.as_view(),
        name="api-recommendations",
    ),
    # Catalog & Admin APIs
    path("api/customers/", CustomersAPI.as_view(), name="api-customers"),
    path("api/categories/", CategoriesAPI.as_view(), name="api-categories"),
    path("api/authors/", AuthorsAPI.as_view(), name="api-authors"),
    path("api/publishers/", PublishersAPI.as_view(), name="api-publishers"),
    path("api/tags/", TagsAPI.as_view(), name="api-tags"),
    # Reviews & Ratings
    path("api/reviews/", ReviewsAPI.as_view(), name="api-reviews"),
    path("api/ratings/", RatingsAPI.as_view(), name="api-ratings"),
    # Health
    path("health/", HealthCheck.as_view(), name="health"),
]
